# Generated by Django 6.0.1 on 2026-04-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_add_delivery_states'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='delivery_state',
        ),
        migrations.AlterField(
            model_name='deliverystate',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Lower = shown first in dropdowns. South states start at 0; UTs end at 60+.'),
        ),
        migrations.AlterField(
            model_name='deliverystate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deliverystate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Inactive states are hidden from both seller UI and customer UI.'),
        ),
        migrations.AlterField(
            model_name='productdeliverystate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('photo', models.ImageField(blank=True, help_text='Square portrait recommended (min 200 × 200 px).', null=True, upload_to='testimonials/')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], db_index=True, default=5)),
                ('description', models.TextField(help_text='The review / testimonial text.')),
                ('is_verified', models.BooleanField(default=True, help_text='Shows a "Verified Buyer" badge on the storefront.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'verbose_name': 'testimonial',
                'verbose_name_plural': 'testimonials',
                'ordering': ['display_order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='app_testimo_is_acti_29d1c4_idx')],
            },
        ),
    ]
