# Generated by Django 6.0.1 on 2026-04-23 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_add_pot_addon_system'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productpotaddon',
            new_name='app_product_plant_p_e66b68_idx',
            old_name='app_productpotaddon_plant_order_idx',
        ),
        migrations.AddField(
            model_name='address',
            name='delivery_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='app.deliverystate'),
        ),
        migrations.AlterField(
            model_name='productpotaddon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
